---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "P@ssw0rd12345"
mysql_db: "wordpress"
mysql_user: "ubuntu"
mysql_password: "P@ssw0rd"

#HTTP Settings
http_host: "host"
http_conf: "host.conf"
http_port: "80"
disable_default: true
